[package]
name = "folkfriend"
version = "3.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
csv = "1.1"
indicatif = "0.16.2"
rayon = "1.5"
rustfft = "6.0.1"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0"
wav = "1.0.0"
